In [3]:
import numpy as np
import pandas as pd

 ### Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 

In [5]:
ar=np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
ar1=ar.reshape(2,5)
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [14]:
ar2=np.arange(1,21)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
print(ar2[5:16])

[ 6  7  8  9 10 11 12 13 14 15 16]


### Exercise 3: (Score : 2) Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. 

In [25]:
S1=pd.Series([3,2,1],index=("apples","bananas","oranges"))
S1

apples     3
bananas    2
oranges    1
dtype: int64

### Exercise 4: (Score : 2) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [30]:
df=pd.DataFrame( {
    "Name": ["Aryan", "Meera", "Rahul", "Sneha", "Kabir", "Priya", "Arjun", "Ananya", "Rohit", "Kavya"],
    "Age": [25, 23, 30, 28, 27, 22, 24, 21, 29, 26],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"]
})
df


Name  Age  Gender
0   Aryan   25    Male
1   Meera   23  Female
2   Rahul   30    Male
3   Sneha   28  Female
4   Kabir   27    Male
5   Priya   22  Female
6   Arjun   24    Male
7  Ananya   21  Female
8   Rohit   29    Male
9   Kavya   26  Female

### . Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [35]:
df["Occupation"] = ["Programmer", "Manager", "Analyst", "Manager", "Analyst", "Analyst", "Programmer", "Programmer", "Manager", "Analyst"]
df

Name  Age  Gender  Occupation
0   Aryan   25    Male  Programmer
1   Meera   23  Female     Manager
2   Rahul   30    Male     Analyst
3   Sneha   28  Female     Manager
4   Kabir   27    Male     Analyst
5   Priya   22  Female     Analyst
6   Arjun   24    Male  Programmer
7  Ananya   21  Female  Programmer
8   Rohit   29    Male     Manager
9   Kavya   26  Female     Analyst

### Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30.

In [40]:
Agefilter=df.loc[df["Age"]>=30]
Agefilter

Name  Age Gender Occupation
2  Rahul   30   Male    Analyst

###  Exercise 7: (Score : 2) Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [43]:
df.to_csv("sample.csv", index=False)

In [45]:
df1=pd.read_csv("sample.csv")
print(df1)

     Name  Age  Gender  Occupation
0   Aryan   25    Male  Programmer
1   Meera   23  Female     Manager
2   Rahul   30    Male     Analyst
3   Sneha   28  Female     Manager
4   Kabir   27    Male     Analyst
5   Priya   22  Female     Analyst
6   Arjun   24    Male  Programmer
7  Ananya   21  Female  Programmer
8   Rohit   29    Male     Manager
9   Kavya   26  Female     Analyst
